services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    volumes:
      # - type: bind
      #   source: src
      #   target: /app
      - type: volume
        source: images
        target: /workspace/images
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:6.0.19-ubuntu2204
    command: --bind_ip=0.0.0.0
    environment:
      MONGO_INITDB_DATABASE: appdb
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: pass 
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_PORT: 27017

volumes:
  dbdata:
  images:
