services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - type: volume
        source: images
        target: /workspace/images
    restart: always
    depends_on:
      - mongodb
      
  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-community-server:6.0.19-ubuntu2204
    command: --noauth --bind_ip_all
    ports:
      - 9000:27017
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    restart: always

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8001:8081
  #   depends_on:
  #     - mongodb
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

volumes:
  dbdata:
  images:
